# Generated by Django 5.0 on 2023-12-17 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Languages',
            new_name='UsedLanguages',
        ),
    ]
